version: "3.8"

services:
  accounts:
    image: asphedaemon/accounts:latest
    deploy:
      resources:
        limits:
          memory: 700M
    ports:
      - "8080:8080"
    networks:
      - netalov

  loans:
    image: asphedaemon/loans:latest
    ports:
      - "8090:8090"
    networks:
      - netalov

  cards:
    image: asphedaemon/cards:latest
    ports:
      - "9000:9000"
    networks:
      - netalov

networks:
  netalov:
    driver: bridge